spring.cloud.config.enabled=false
spring.application.name=eureka-server-auth
server.port=8767

spring.security.user.name=admin
spring.security.user.password=admin123

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false